### ISSUE TITLE
R-Car E3

### ISSUE THREAD

**Issue by Samuellee1986** [renesas-rcar/meta-renesas#14]
I'am try to compile image for R-CarE3 under your guide, but failed with the following information:

MACHINE=r8a77990 is invalid. Please set a valid MACHINE in your local.conf, environment or other configuration file.

Please help me with what other configures I should modify.

**Comment by patersonc** [comment]
Hello @Samuellee1986,
You need to set MACHINE to a valid value. The supported machine names can be found in meta-renesas/meta-rcar-gen3/conf/machine/.

For R-Car E3, the supported platform is "Ebisu", so assuming you're using Roko or newer you should set MACHINE=ebisu.

Kind regards, Chris

**Comment by Samuellee1986** [comment]
> Hello @Samuellee1986,
> You need to set MACHINE to a valid value. The supported machine names can be found in meta-renesas/meta-rcar-gen3/conf/machine/.
> 
> For R-Car E3, the supported platform is "Ebisu", so assuming you're using Roko or newer you should set MACHINE=ebisu.
> 
> Kind regards, Chris

Thank you very mush, I Just found the reason too and begin to compile

**Comment by patersonc** [comment]
Happy days :)
