### ISSUE TITLE
remove "PACKAGECONFIG_remove" for timesyncd

### ISSUE THREAD

**Issue by Siddius** [renesas-rcar/meta-renesas#20]
A "PACKAGECONFIG_remove" should only be used as last resort becaus it cant be readded by any other layer. Therefor i would like to see this line removed. I also dont see any benifit in it.

https://github.com/renesas-rcar/meta-renesas/blob/32e34de56a7962efa45725b3db5838b07adca06f/meta-rcar-gen3/recipes-core/systemd/systemd_%25.bbappend#L5

**Comment by khangnguyenrvc** [comment]
Hello @Siddius,

Thank you for your feedback, this modification is for internal use cases,
But now, we are considering its necessity for the next release version.

**Comment by Siddius** [comment]
Hello @khangnguyenrvc 

if it's possible for your internal project maybe you can move it to another layer ? The Problem here is really that you can't overwrite a remove in another layer. So i have to patch this repo. I think this remove should not be here if its must have requirement in order to build recipies from this layer.

**Comment by khangnguyenrvc** [comment]
Hello @Siddius 

> if it's possible for your internal project maybe you can move it to another layer ?

I plan to update this point in next push, please kindly wait for it,

> The Problem here is really that you can't overwrite a remove in another layer. So i have to patch this repo

I understand your problem, it removes systemd-timesync module from rootfs, and the user can not
reset this config from their layer.

**Comment by khangnguyenrvc** [comment]
Hi @Siddius 

The "PACKAGECONFIG_remove for timesyncd" was removed in https://github.com/renesas-rcar/meta-renesas/commit/ac08e0b298e45f254b976b678690732c3ebd1f32

**Comment by Siddius** [comment]
@khangnguyenrvc Thanks
