### ISSUE TITLE
Fetcher failure: Unable to find file file://r8a77951_linux_gsx_binaries_gles.tar.bz2

### ISSUE THREAD

**Issue by arkceajin** [renesas-rcar/meta-renesas#21]
Hello all,

I am getting below error when compiling Salvator-x.
`ERROR: gles-user-module-1.0-r0 do_fetch: Fetcher failure: Unable to find file file://r8a77951_linux_gsx_binaries_gles.tar.bz2 anywhere.`
so any idea about this?
BTW why it fetching the `file://...` local path, I searched the whole source there no such file.
`file ./ -name *linux_gsx_binaries_gles*`

**Comment by KhiemNguyenT** [comment]
Hi @arkceajin ,

Please find the evaluation packages at https://elinux.org/R-Car/Boards/Yocto-Gen3.
There are some instructions to perform Yocto build with those packages.

Hope it help

**Comment by arkceajin** [comment]
Hi @KhiemNguyenT 

Thank you, I found the missing driver, and I am able to continue to compile.
So it has to download manually?

**Comment by KhiemNguyenT** [comment]
Hi @arkceajin ,

Yes.
You need to go through the registration and agree the license to use the evaluation packages.

**Comment by arkceajin** [comment]
solved

**Comment by Saicharanguda** [comment]
Hello all,
I am trying to build yocto weston  image for salvator xs board while building I am missing this package 
The error indicates an issue with unpacking the r8a77965_linux_gsx_binaries_gles.tar.bz2 and GSX_KM_M3N.tar.bz2 files.

**Comment by DuyDang007** [comment]
Hi @Saicharanguda 
Just to make sure, did you download the graphic and multimedia packages to your build tree?
If not, please follow the guide in: https://elinux.org/R-Car/Boards/Yocto-Gen3/v5.9.4#Required_packages

If you have downloaded and got build issue, please show me your error log

**Comment by Jarvis3737** [comment]
Hi all,
I am facing same issue 
ERROR: gles-user-module-1.0-r0 do_fetch: Fetcher failure: Unable to find file file://r8a77951_linux_gsx_binaries_gles.tar.bz2 anywhere.
But I am trying to build for Xen(with RCar BSP) using below wiki page.
https://wiki.xenproject.org/wiki/Xen_ARM_with_Virtualization_Extensions/Salvator-XS

In this page it recommends to avoid downloading package mentioned in  https://elinux.org/R-Car/Boards/Yocto-Gen3/v5.9.4#Required_packages

In this case I am bit perplexed how to proceed?? can anyone suggest me solution here or improve my understanding?

**Comment by DuyDang007** [comment]
Hi @Chandrashekherpurohit ,

The build guide in Xen project wiki has this step different from eLinux:

> In build step #8 change the path to local.conf file:
> ```
> cp $WORK/meta-renesas/meta-rcar-gen3/docs/sample/conf/salvator-x/poky-gcc/bsp/*.conf ./conf/
> cd $WORK/build
> cp conf/local-wayland.conf conf/local.conf
> ```

I think you missed it, and the build still searched for graphics and multimedia packages.
Please note the different path:
```diff
-meta-renesas/meta-rcar-gen3/docs/sample/conf/salvator-x/poky-gcc/bsp/*.conf
+meta-renesas/meta-rcar-gen3/docs/sample/conf/salvator-x/poky-gcc/mmp/*.conf
```

**Comment by Jarvis3737** [comment]
> Hi [@Chandrashekherpurohit](https://github.com/Chandrashekherpurohit) ,
> 
> The build guide in Xen project wiki has this step different from eLinux:
> 
> > In build step [#8](https://github.com/renesas-rcar/meta-renesas/issues/8) change the path to local.conf file:
> > ```
> > cp $WORK/meta-renesas/meta-rcar-gen3/docs/sample/conf/salvator-x/poky-gcc/bsp/*.conf ./conf/
> > cd $WORK/build
> > cp conf/local-wayland.conf conf/local.conf
> > ```
> 
> I think you missed it, and the build still searched for graphics and multimedia packages. Please note the different path:
> 
> -meta-renesas/meta-rcar-gen3/docs/sample/conf/salvator-x/poky-gcc/bsp/*.conf
> +meta-renesas/meta-rcar-gen3/docs/sample/conf/salvator-x/poky-gcc/mmp/*.conf

@DuyDang007 thanks for quick reply. I think I did this step with "mmp" . but I will cross-check one more time and get back to you.
