### ISSUE TITLE
Fix md5sum on license in dunfell branch

### ISSUE THREAD

**Issue by feilz** [renesas-rcar/meta-renesas#28]
Found an issue when building this layer today, that for **meta-rcar-gen3e/recipes-kernel/kernel-module-gles.bb** there's wrong md5sum from license file GPL-COPYING.

Correct md5sum is 60422928ba677faaa13d6ab5f5baaa1e

I can solve this for now with .bbappend, but hope I can remove that asap.
I wasn't able to download and to create a pull request of this myself, so hope someone who has the privileges does this

**Comment by DuyDang007** [comment]
Hi @feilz ,

The md5sum value is for new version of gles kernel module. However, the new package was not released yet.
We expect in October. Please wait for it.
