### ISSUE TITLE
which version is for CR7?

### ISSUE THREAD

**Issue by arkceajin** [renesas-rcar/meta-renesas#39]
I want to use CR7 kicks Linux to boot, which version shall I uses?
I found only two Renesas-Yocto-v5.9.x-SafeRendering tags, is there a branch that can enable 
MACHINE_FEATURES_append = " safe-rendering"

and it would like nice if the branch supported kirkstone

**Comment by DuyDang007** [comment]
Hi @arkceajin ,

For this question, I recommend you to use Renesas Engineering Community forum: https://community.renesas.com/automotive/r-car-h3-m3-cockpit/
